laserscan_kinect:
  ros__parameters:
    # Frame id for the output laserscan.
    output_frame_id: oak_rgb_camera_frame
    # Minimum sensor range (m).
    range_min: 0.4
    # Maximum sensor range (m).
    range_max: 10.0
    # Height of used part of depth img (px).
    scan_height: 50
    # Row step in depth image processing (px).
    depth_img_row_step: 20
    # If continously camera data update.
    cam_model_update: false

    # Height of sensor optical center mount (m).
    sensor_mount_height: 0.8
    # Sensor tilt angle compensation.
    sensor_tilt_angle: 0.0
    # Remove ground from scan.
    ground_remove_en: false
    # Ground margin (m).
    ground_margin: 0.05
    # Sensor tilt angle compensation.
    tilt_compensation_en: false

    publish_dbg_info: true
    threads_num: 1
    filter_mode: median
