 
name: RAE ROS CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - humble
    tags:
      - 'v*'
  pull_request:
    branches:
      - humble
env:
  ROS_DISTRO: humble

jobs:
  docker-build:
    name: Build and Upload to Docker Hub
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write
    env: 
      PUSH:  ${{ (github.event_name != 'pull_request') && (github.repository == 'luxonis/rae-ros') && startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Version
        if: env.PUSH == 'true'
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - name: Build Robot
        uses: docker/build-push-action@v3
        if: env.PUSH == 'false'
        with:
          build-args: |
            ROS_DISTRO=${{ env.ROS_DISTRO }}
            USE_RVIZ=0
            SIM=0
          platforms: |
            arm64
            amd64
          push: ${{ env.PUSH }}
          no-cache: true

      - name: Build and Push Robot
        uses: docker/build-push-action@v3
        if: env.PUSH == 'true'
        with:
          build-args: |
            ROS_DISTRO=${{ env.ROS_DISTRO }}
            USE_RVIZ=0
            SIM=0
          platforms: |
            arm64
            amd64
          push: ${{ env.PUSH }}
          no-cache: true
          tags: | 
            ghcr.io/luxonis/rae-ros:${{ steps.vars.outputs.short_ref }}
